---
  version: '3.7'

  services:

    joomla:
      image: joomla:php7.3
      container_name: joomla
      restart: always
      environment:
        - JOOMLA_DB_HOST=db
        - JOOMLA_DB_USER=root
        - JOOMLA_DB_PASSWORD=mysql
        - JOOMLA_DB_NAME=joomla
      ports:
        - 80:80
      volumes:
        - type: bind
          source: ./joomla/html
          target: /var/www/html
      depends_on:
        - db

    db:
      image: mysql:5.7
      container_name: mysql
      restart: always
      ports: []
      volumes:
        - type: bind
          source: ./joomla/db
          target: /var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=mysql

    phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_HOST=db

  volumes:
    joomla:
    mysql:
