---
  version: '3.7'

  services:

    joomla:
      image: joomla:php7.3
      container_name: joomla
      restart: always
      environment:
        - JOOMLA_DB_HOST=db
        - JOOMLA_DB_USER=root
        - JOOMLA_DB_PASSWORD=mysql
        - JOOMLA_DB_NAME=joomla
      ports:
        - 80:80
      volumes:
        - type: bind
          source: ./joomla/html
          target: /var/www/html
        - type: bind
          source: ./dev
          target: /var/www/html/dev
          read_only: true
      depends_on:
        - db

    db:
      image: mysql:5.7
      container_name: joomla_mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
      ports: []
      volumes:
        - type: bind
          source: ./joomla/db
          target: /var/lib/mysql

    phpmyadmin:
      image: phpmyadmin
      container_name: joomla_phpmyadmin
      restart: always
      environment:
        - PMA_HOST=db
      ports:
        - 8080:80
      volumes: []
