---
  version: '3.7'

  services:

    joomla:
      image: joomla:php7.3
      restart: always
      environment:
        - JOOMLA_DB_HOST=db
        - JOOMLA_DB_USER=root
        - JOOMLA_DB_PASSWORD=mysql
        - JOOMLA_DB_NAME=joomla
      ports:
        - 80:80
      volumes:
        - ./joomla/html:/var/www/html
        # - ./makedb.php:/makedb.php
      depends_on:
        - db

    db:
      image: mysql:5.7
      restart: always
      ports: []
      volumes:
        - ./joomla/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=mysql

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_HOST=db
